FROM liquibase/liquibase:latest

USER root
RUN apt-get update && \
    apt-get install -y curl && \
    mkdir -p /liquibase/lib && \
    curl -L https://jdbc.postgresql.org/download/postgresql-42.7.3.jar -o /liquibase/lib/postgresql.jar && \
    chown -R liquibase:liquibase /liquibase/lib && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER liquibase
WORKDIR /liquibase/changelog
